export type GaleryPostTypes = {
  image: string,
  title: string,
  description: string,
  like: number,
  comment: number,
  id: number,
}

export const GaleryInfos: GaleryPostTypes[] = [
  {
    image: '/galery-images/Image.png',
    title: 'Explorando Novos Horizontes Musicais',
    description: 'Essa foto captura o momento em que mergulhamos na realidade virtual da #OneBitMusic. Foi uma experiência incrível explorar novos horizontes musicais e nos conectar com artistas de todo o mundo. Veja como nossos fãs estão aproveitando essa jornada musical!',
    like: 1234,
    comment: 11,
    id: 0,
  },
  {
    image: '/galery-images/Image2.png',
    title: 'Vibrações Eletrizantes na OneBitMusic',
    description: 'Uma imagem que captura a energia contagiante do show digital da #OneBitMusic. Os visuais hipnotizantes e a batida pulsante nos transportaram para uma jornada musical incrível. Compartilhe suas fotos e faça parte da nossa galeria de fãs!',
    like: 2434,
    comment: 140,
    id: 1,
  },
  {
    image: '/galery-images/Image3.png',
    title: 'Noite Inesquecível com OneBitMusic',
    description: 'Uma foto do incrível show de realidade virtual da #OneBitMusic, onde a música e a tecnologia se encontram para criar uma experiência única. Obrigado a todos que compartilharam esse momento conosco!',
    like: 5234,
    comment: 29,
    id: 2,
  },
  {
    image: '/galery-images/Image4.png',
    title: 'A Magia da Música em Realidade Virtual',
    description: 'Essa foto é um lembrete da magia que encontramos nos shows digitais da #OneBitMusic. Os óculos de realidade virtual nos transportam para um mundo sonoro único, onde a música ganha vida. Veja como nossos fãs estão aproveitando essa experiência imersiva!',
    like: 3334,
    comment: 12,
    id: 3,
  },
  {
    image: '/galery-images/Image5.png',
    title: 'Momentos Inesquecíveis na OneBitMusic',
    description: 'Essa imagem representa a alegria e a emoção que experimentamos nos shows da #OneBitMusic. A música nos conecta, nos inspira e nos proporciona momentos inesquecíveis. Compartilhe suas fotos conosco e faça parte dessa galeria de momentos especiais!',
    like: 1034,
    comment: 19,
    id: 4,
  },
  {
    image: '/galery-images/Image17.png',
    title: 'Explorando Novos Horizontes Musicais',
    description: 'Essa foto captura o momento em que mergulhamos na realidade virtual da #OneBitMusic. Foi uma experiência incrível explorar novos horizontes musicais e nos conectar com artistas de todo o mundo. Veja como nossos fãs estão aproveitando essa jornada musical!',
    like: 8234,
    comment: 151,
    id: 11,
  },
  {
    image: '/galery-images/Image18.png',
    title: 'A Magia da Música em Realidade Virtual',
    description: 'Essa foto é um lembrete da magia que encontramos nos shows digitais da #OneBitMusic. Os óculos de realidade virtual nos transportam para um mundo sonoro único, onde a música ganha vida. Veja como nossos fãs estão aproveitando essa experiência imersiva!',
    like: 2104,
    comment: 612,
    id: 12,
  },
  {
    image: '/galery-images/Image19.png',
    title: 'Vibrações Eletrizantes na OneBitMusic',
    description: 'Uma imagem que captura a energia contagiante do show digital da #OneBitMusic. Os visuais hipnotizantes e a batida pulsante nos transportaram para uma jornada musical incrível. Compartilhe suas fotos e faça parte da nossa galeria de fãs!',
    like: 1634,
    comment: 5140,
    id: 13,
  },
  {
    image: '/galery-images/Image20.png',
    title: 'Momentos Inesquecíveis na OneBitMusic',
    description: 'Essa imagem representa a alegria e a emoção que experimentamos nos shows da #OneBitMusic. A música nos conecta, nos inspira e nos proporciona momentos inesquecíveis. Compartilhe suas fotos conosco e faça parte dessa galeria de momentos especiais!',
    like: 834,
    comment: 719,
    id: 14,
  },
]