export const GaleryInfos = [
  {
    image: '/galery-images/Img.png',
    title: 'Explorando Novos Horizontes Musicais',
    description: 'Essa foto captura o momento em que mergulhamos na realidade virtual da #OneBitMusic. Foi uma experiência incrível explorar novos horizontes musicais e nos conectar com artistas de todo o mundo. Veja como nossos fãs estão aproveitando essa jornada musical!',
    like: 80,
    comment: 11,
  },
  {
    image: '/galery-images/Img2.png',
    title: 'Vibrações Eletrizantes na OneBitMusic',
    description: 'Uma imagem que captura a energia contagiante do show digital da #OneBitMusic. Os visuais hipnotizantes e a batida pulsante nos transportaram para uma jornada musical incrível. Compartilhe suas fotos e faça parte da nossa galeria de fãs!',
    like: 321,
    comment: 140,
  },
  {
    image: '/galery-images/Img3.png',
    title: 'Noite Inesquecível com OneBitMusic',
    description: 'Uma foto do incrível show de realidade virtual da #OneBitMusic, onde a música e a tecnologia se encontram para criar uma experiência única. Obrigado a todos que compartilharam esse momento conosco!',
    like: 1.029,
    comment: 29,
  },
  {
    image: '/galery-images/Img4.png',
    title: 'A Magia da Música em Realidade Virtual',
    description: 'Essa foto é um lembrete da magia que encontramos nos shows digitais da #OneBitMusic. Os óculos de realidade virtual nos transportam para um mundo sonoro único, onde a música ganha vida. Veja como nossos fãs estão aproveitando essa experiência imersiva!',
    like: 103,
    comment: 12,
  },
  {
    image: '/galery-images/Img5.png',
    title: 'Momentos Inesquecíveis na OneBitMusic',
    description: 'Essa imagem representa a alegria e a emoção que experimentamos nos shows da #OneBitMusic. A música nos conecta, nos inspira e nos proporciona momentos inesquecíveis. Compartilhe suas fotos conosco e faça parte dessa galeria de momentos especiais!',
    like: 78,
    comment: 19,
  },
  {
    image: '/galery-images/Img6.png',
    title: 'Noite Inesquecível com OneBitMusic',
    description: 'Uma foto do incrível show de realidade virtual da #OneBitMusic, onde a música e a tecnologia se encontram para criar uma experiência única. Obrigado a todos que compartilharam esse momento conosco!',
    like: 1.029,
    comment: 29,
  },
  {
    image: '/galery-images/Img7.png',
    title: 'Explorando Novos Horizontes Musicais',
    description: 'Essa foto captura o momento em que mergulhamos na realidade virtual da #OneBitMusic. Foi uma experiência incrível explorar novos horizontes musicais e nos conectar com artistas de todo o mundo. Veja como nossos fãs estão aproveitando essa jornada musical!',
    like: 80,
    comment: 11,
  },
  {
    image: '/galery-images/Img8.png',
    title: 'A Magia da Música em Realidade Virtual',
    description: 'Essa foto é um lembrete da magia que encontramos nos shows digitais da #OneBitMusic. Os óculos de realidade virtual nos transportam para um mundo sonoro único, onde a música ganha vida. Veja como nossos fãs estão aproveitando essa experiência imersiva!',
    like: 103,
    comment: 12,
  },
  {
    image: '/galery-images/Img9.png',
    title: 'Vibrações Eletrizantes na OneBitMusic',
    description: 'Uma imagem que captura a energia contagiante do show digital da #OneBitMusic. Os visuais hipnotizantes e a batida pulsante nos transportaram para uma jornada musical incrível. Compartilhe suas fotos e faça parte da nossa galeria de fãs!',
    like: 321,
    comment: 140,
  },
  {
    image: '/galery-images/Img10.png',
    title: 'Momentos Inesquecíveis na OneBitMusic',
    description: 'Essa imagem representa a alegria e a emoção que experimentamos nos shows da #OneBitMusic. A música nos conecta, nos inspira e nos proporciona momentos inesquecíveis. Compartilhe suas fotos conosco e faça parte dessa galeria de momentos especiais!',
    like: 78,
    comment: 19,
  },
]